---
kind: Endpoints
apiVersion: v1
metadata:
  name: grafana
subsets:
  - addresses:
      - ip: 172.22.127.171
    ports:
      - port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scc-grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: grafana.xxlaila.cn
    http:
      paths:
      - path:
        backend:
          serviceName: grafana
          servicePort: 3000
